export * from 'components/head'
export * from 'components/playlist'
export * from 'components/player'
export * from 'components/sample'
export * from 'components/wrap'
export * from 'components/container'
export * from 'components/title'

export * from 'components/page'
export * from 'components/page/hero'
export * from 'components/page/intro'
export * from 'components/page/studio'
export * from 'components/page/footer'
export * from 'components/page/testimonials'
export * from 'components/page/logos'